/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestesRouteImport } from './routes/testes'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ResultadosRouteImport } from './routes/resultados'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MeusBusRouteImport } from './routes/meus-bus'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as CapturarRouteImport } from './routes/capturar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicV1TotaisRouteImport } from './routes/api/public/v1/totais'
import { Route as ApiPublicV1CoberturaRouteImport } from './routes/api/public/v1/cobertura'
import { Route as ApiPublicHooksSyncChavesTseRouteImport } from './routes/api/public/hooks/sync-chaves-tse'
import { Route as ApiPublicHooksRevalidarChavesRouteImport } from './routes/api/public/hooks/revalidar-chaves'
import { Route as ApiPublicV1BoletinsIdRouteImport } from './routes/api/public/v1/boletins.$id'

const TestesRoute = TestesRouteImport.update({
  id: '/testes',
  path: '/testes',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadosRoute = ResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusBusRoute = MeusBusRouteImport.update({
  id: '/meus-bus',
  path: '/meus-bus',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const CapturarRoute = CapturarRouteImport.update({
  id: '/capturar',
  path: '/capturar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1TotaisRoute = ApiPublicV1TotaisRouteImport.update({
  id: '/api/public/v1/totais',
  path: '/api/public/v1/totais',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1CoberturaRoute = ApiPublicV1CoberturaRouteImport.update({
  id: '/api/public/v1/cobertura',
  path: '/api/public/v1/cobertura',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncChavesTseRoute =
  ApiPublicHooksSyncChavesTseRouteImport.update({
    id: '/api/public/hooks/sync-chaves-tse',
    path: '/api/public/hooks/sync-chaves-tse',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRevalidarChavesRoute =
  ApiPublicHooksRevalidarChavesRouteImport.update({
    id: '/api/public/hooks/revalidar-chaves',
    path: '/api/public/hooks/revalidar-chaves',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1BoletinsIdRoute = ApiPublicV1BoletinsIdRouteImport.update({
  id: '/api/public/v1/boletins/$id',
  path: '/api/public/v1/boletins/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/capturar': typeof CapturarRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/meus-bus': typeof MeusBusRoute
  '/perfil': typeof PerfilRoute
  '/resultados': typeof ResultadosRoute
  '/sobre': typeof SobreRoute
  '/testes': typeof TestesRoute
  '/api/public/hooks/revalidar-chaves': typeof ApiPublicHooksRevalidarChavesRoute
  '/api/public/hooks/sync-chaves-tse': typeof ApiPublicHooksSyncChavesTseRoute
  '/api/public/v1/cobertura': typeof ApiPublicV1CoberturaRoute
  '/api/public/v1/totais': typeof ApiPublicV1TotaisRoute
  '/api/public/v1/boletins/$id': typeof ApiPublicV1BoletinsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/capturar': typeof CapturarRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/meus-bus': typeof MeusBusRoute
  '/perfil': typeof PerfilRoute
  '/resultados': typeof ResultadosRoute
  '/sobre': typeof SobreRoute
  '/testes': typeof TestesRoute
  '/api/public/hooks/revalidar-chaves': typeof ApiPublicHooksRevalidarChavesRoute
  '/api/public/hooks/sync-chaves-tse': typeof ApiPublicHooksSyncChavesTseRoute
  '/api/public/v1/cobertura': typeof ApiPublicV1CoberturaRoute
  '/api/public/v1/totais': typeof ApiPublicV1TotaisRoute
  '/api/public/v1/boletins/$id': typeof ApiPublicV1BoletinsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/capturar': typeof CapturarRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/meus-bus': typeof MeusBusRoute
  '/perfil': typeof PerfilRoute
  '/resultados': typeof ResultadosRoute
  '/sobre': typeof SobreRoute
  '/testes': typeof TestesRoute
  '/api/public/hooks/revalidar-chaves': typeof ApiPublicHooksRevalidarChavesRoute
  '/api/public/hooks/sync-chaves-tse': typeof ApiPublicHooksSyncChavesTseRoute
  '/api/public/v1/cobertura': typeof ApiPublicV1CoberturaRoute
  '/api/public/v1/totais': typeof ApiPublicV1TotaisRoute
  '/api/public/v1/boletins/$id': typeof ApiPublicV1BoletinsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/capturar'
    | '/insights'
    | '/login'
    | '/mapa'
    | '/meus-bus'
    | '/perfil'
    | '/resultados'
    | '/sobre'
    | '/testes'
    | '/api/public/hooks/revalidar-chaves'
    | '/api/public/hooks/sync-chaves-tse'
    | '/api/public/v1/cobertura'
    | '/api/public/v1/totais'
    | '/api/public/v1/boletins/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/capturar'
    | '/insights'
    | '/login'
    | '/mapa'
    | '/meus-bus'
    | '/perfil'
    | '/resultados'
    | '/sobre'
    | '/testes'
    | '/api/public/hooks/revalidar-chaves'
    | '/api/public/hooks/sync-chaves-tse'
    | '/api/public/v1/cobertura'
    | '/api/public/v1/totais'
    | '/api/public/v1/boletins/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/capturar'
    | '/insights'
    | '/login'
    | '/mapa'
    | '/meus-bus'
    | '/perfil'
    | '/resultados'
    | '/sobre'
    | '/testes'
    | '/api/public/hooks/revalidar-chaves'
    | '/api/public/hooks/sync-chaves-tse'
    | '/api/public/v1/cobertura'
    | '/api/public/v1/totais'
    | '/api/public/v1/boletins/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CapturarRoute: typeof CapturarRoute
  InsightsRoute: typeof InsightsRoute
  LoginRoute: typeof LoginRoute
  MapaRoute: typeof MapaRoute
  MeusBusRoute: typeof MeusBusRoute
  PerfilRoute: typeof PerfilRoute
  ResultadosRoute: typeof ResultadosRoute
  SobreRoute: typeof SobreRoute
  TestesRoute: typeof TestesRoute
  ApiPublicHooksRevalidarChavesRoute: typeof ApiPublicHooksRevalidarChavesRoute
  ApiPublicHooksSyncChavesTseRoute: typeof ApiPublicHooksSyncChavesTseRoute
  ApiPublicV1CoberturaRoute: typeof ApiPublicV1CoberturaRoute
  ApiPublicV1TotaisRoute: typeof ApiPublicV1TotaisRoute
  ApiPublicV1BoletinsIdRoute: typeof ApiPublicV1BoletinsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testes': {
      id: '/testes'
      path: '/testes'
      fullPath: '/testes'
      preLoaderRoute: typeof TestesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultados': {
      id: '/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof ResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-bus': {
      id: '/meus-bus'
      path: '/meus-bus'
      fullPath: '/meus-bus'
      preLoaderRoute: typeof MeusBusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capturar': {
      id: '/capturar'
      path: '/capturar'
      fullPath: '/capturar'
      preLoaderRoute: typeof CapturarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/totais': {
      id: '/api/public/v1/totais'
      path: '/api/public/v1/totais'
      fullPath: '/api/public/v1/totais'
      preLoaderRoute: typeof ApiPublicV1TotaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/cobertura': {
      id: '/api/public/v1/cobertura'
      path: '/api/public/v1/cobertura'
      fullPath: '/api/public/v1/cobertura'
      preLoaderRoute: typeof ApiPublicV1CoberturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-chaves-tse': {
      id: '/api/public/hooks/sync-chaves-tse'
      path: '/api/public/hooks/sync-chaves-tse'
      fullPath: '/api/public/hooks/sync-chaves-tse'
      preLoaderRoute: typeof ApiPublicHooksSyncChavesTseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/revalidar-chaves': {
      id: '/api/public/hooks/revalidar-chaves'
      path: '/api/public/hooks/revalidar-chaves'
      fullPath: '/api/public/hooks/revalidar-chaves'
      preLoaderRoute: typeof ApiPublicHooksRevalidarChavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/boletins/$id': {
      id: '/api/public/v1/boletins/$id'
      path: '/api/public/v1/boletins/$id'
      fullPath: '/api/public/v1/boletins/$id'
      preLoaderRoute: typeof ApiPublicV1BoletinsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CapturarRoute: CapturarRoute,
  InsightsRoute: InsightsRoute,
  LoginRoute: LoginRoute,
  MapaRoute: MapaRoute,
  MeusBusRoute: MeusBusRoute,
  PerfilRoute: PerfilRoute,
  ResultadosRoute: ResultadosRoute,
  SobreRoute: SobreRoute,
  TestesRoute: TestesRoute,
  ApiPublicHooksRevalidarChavesRoute: ApiPublicHooksRevalidarChavesRoute,
  ApiPublicHooksSyncChavesTseRoute: ApiPublicHooksSyncChavesTseRoute,
  ApiPublicV1CoberturaRoute: ApiPublicV1CoberturaRoute,
  ApiPublicV1TotaisRoute: ApiPublicV1TotaisRoute,
  ApiPublicV1BoletinsIdRoute: ApiPublicV1BoletinsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
